language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
matrix:
  include:
  - name: "Style check"
    env: TEST_SUITE='pmd:pmd pmd:cpd pmd:check pmd:cpd-check -Dpmd.printFailingErrors'
  - name: "Javadoc"
    env: TEST_SUITE='javadoc:jar'
  - name: "Unit tests"
    env: TEST_SUITE='test jacoco:report coveralls:report'
  - name: "Integration tests"
    env: TEST_SUITE='test-compile license:check failsafe:integration-test failsafe:verify'
script:
  - mvn -P travis $TEST_SUITE -B
